export const GENRES = [
  { id: '', label: 'Svi žanrovi' },
  { id: '28', label: 'Akcija' },
  { id: '12', label: 'Avantura' },
  { id: '16', label: 'Animacija' },
  { id: '35', label: 'Komedija' },
  { id: '80', label: 'Kriminalistički' },
  { id: '99', label: 'Dokumentarni' },
  { id: '18', label: 'Drama' },
  { id: '10751', label: 'Porodični' },
  { id: '14', label: 'Fantazija' },
  { id: '36', label: 'Istorijski' },
  { id: '27', label: 'Horor' },
  { id: '10402', label: 'Muzički' },
  { id: '9648', label: 'Misterija' },
  { id: '10749', label: 'Romantični' },
  { id: '878', label: 'Naučna fantastika' },
  { id: '10770', label: 'TV film' },
  { id: '53', label: 'Triler' },
  { id: '10752', label: 'Ratni' },
  { id: '37', label: 'Vestern' },
];
